# Tag List effect on ratings : Sheryl Boateng

In [11]:
import pandas as pd
import ast

In [12]:
makeup_data = pd.read_csv("/Users/sherylboateng/Desktop/TEPP_Data_Project/data/processed/clean_makeup.csv")

makeup_data.info()
makeup_data.describe().round()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 931 entries, 0 to 930
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            931 non-null    int64
 1   brand         919 non-null    object
 2   name          931 non-null    object
 3   category      507 non-null    object
 4   product_type  931 non-null    object
 5   price         917 non-null    float64
 6   currency      368 non-null    object
 7   tag_list      931 non-null    object
 8   rating        340 non-null    float64
dtypes: float64(2), int64(1), object(6)
memory usage: 65.6+ KB

           id  price  rating
count   931.0  917.0   340.0
mean    531.0   17.0     4.0
std     311.0   11.0     1.0
min       1.0    0.0     2.0
25%     263.0    9.0     4.0
50%     518.0   14.0     4.0
75%     814.0   22.0     5.0
max    1048.0   77.0     5.0

## Data Cleaning

Major problem here pandas is counting different columns with the same tags because they are in different orders.

In [13]:
no_nan_values = makeup_data[makeup_data['rating'].notna() & (makeup_data['tag_list'] != '[]')]

no_nan_values['tag_list'].value_counts()

tag_list
['Gluten Free']                                                                                         29
['Vegan']                                                                                               23
['Canadian', 'Natural']                                                                                 18
['Gluten Free', 'Natural']                                                                              11
['Natural']                                                                                             10
['Vegan', 'Natural']                                                                                     7
['Vegan', 'Gluten Free', 'Natural']                                                                      6
['Canadian']                                                                                             4
['Natural', 'Gluten Free']                                                                               4
['Canadian', 'Gluten Free']                                                                              3
['Natural', 'Vegan', 'Gluten Free', 'Non-GMO', 'Canadian']                                               3
['Canadian', 'Vegan', 'Natural']                                                                         2
['Organic', 'Natural']                                                                                   2
['Natural', 'Vegan']                                                                                     2
['Natural', 'Vegan', 'Gluten Free', 'Fair Trade', 'Sugar Free', 'Non-GMO', 'Dairy Free', 'Canadian']     2
['Natural', 'Organic', 'Vegan', 'Gluten Free', 'Canadian']                                               1
['Natural', 'Gluten Free', 'Non-GMO', 'Peanut Free Product', 'Canadian']                                 1
['Natural', 'Organic', 'Gluten Free', 'Canadian']                                                        1
['Natural', 'Canadian']                                                                                  1
['Natural', 'Vegan', 'Canadian']                                                                         1
['Natural', 'Gluten Free', 'Canadian']                                                                   1
Name: count, dtype: int64

In [14]:
for index, row in no_nan_values.iterrows():
        str_list = row['tag_list']
        new_list = ast.literal_eval(str_list)
        sorted_list = sorted(new_list)
        tupled_list = tuple(sorted_list)
        no_nan_values.at[index, 'tag_list'] = tupled_list
        print(sorted_list)

['Gluten Free', 'Natural']
['Canadian', 'Natural']
['Gluten Free']
['Vegan']
['Gluten Free', 'Natural']
['Natural']
['Canadian', 'Natural']
['Gluten Free']
['Vegan']
['Natural']
['Gluten Free']
['Natural', 'Organic']
['Gluten Free', 'Natural']
['Gluten Free']
['Gluten Free']
['Gluten Free']
['Canadian', 'Natural']
['Gluten Free']
['Gluten Free']
['Vegan']
['Canadian', 'Natural']
['Gluten Free', 'Natural']
['Canadian', 'Gluten Free', 'Natural', 'Non-GMO', 'Vegan']
['Vegan']
['Gluten Free']
['Canadian']
['Canadian', 'Natural']
['Gluten Free']
['Canadian', 'Gluten Free']
['Vegan']
['Gluten Free', 'Natural', 'Vegan']
['Canadian']
['Gluten Free']
['Gluten Free']
['Natural']
['Vegan']
['Gluten Free', 'Natural']
['Gluten Free']
['Gluten Free']
['Gluten Free']
['Canadian', 'Natural']
['Gluten Free']
['Canadian', 'Natural']
['Gluten Free', 'Natural']
['Canadian', 'Natural']
['Gluten Free']
['Gluten Free']
['Natural', 'Vegan']
['Vegan']
['Canadian', 'Natural']
['Vegan']
['Natural']
['Gluten Free', 'Natural', 'Vegan']
['Gluten Free']
['Vegan']
['Gluten Free']
['Gluten Free']
['Natural', 'Vegan']
['Vegan']
['Natural']
['Natural', 'Vegan']
['Canadian']
['Vegan']
['Gluten Free', 'Natural', 'Vegan']
['Canadian', 'Natural']
['Gluten Free', 'Natural', 'Vegan']
['Gluten Free']
['Canadian', 'Gluten Free', 'Natural', 'Non-GMO', 'Vegan']
['Natural', 'Vegan']
['Gluten Free', 'Natural']
['Gluten Free', 'Natural', 'Vegan']
['Canadian']
['Gluten Free']
['Gluten Free']
['Gluten Free', 'Natural', 'Vegan']
['Canadian', 'Natural']
['Canadian', 'Natural', 'Vegan']
['Canadian', 'Gluten Free']
['Gluten Free', 'Natural']
['Gluten Free']
['Canadian', 'Gluten Free', 'Natural', 'Organic', 'Vegan']
['Gluten Free']
['Natural', 'Vegan']
['Canadian', 'Natural', 'Vegan']
['Vegan']
['Vegan']
['Vegan']
['Gluten Free']
['Vegan']
['Canadian', 'Dairy Free', 'Fair Trade', 'Gluten Free', 'Natural', 'Non-GMO', 'Sugar Free', 'Vegan']
['Vegan']
['Canadian', 'Dairy Free', 'Fair Trade', 'Gluten Free', 'Natural', 'Non-GMO', 'Sugar Free', 'Vegan']
['Vegan']
['Vegan']
['Natural']
['Canadian', 'Natural']
['Canadian', 'Natural']
['Natural', 'Vegan']
['Canadian', 'Natural']
['Canadian', 'Gluten Free', 'Natural', 'Non-GMO', 'Vegan']
['Gluten Free', 'Natural']
['Canadian', 'Natural']
['Canadian', 'Natural']
['Natural']
['Canadian', 'Natural']
['Natural', 'Organic']
['Gluten Free']
['Canadian', 'Natural']
['Natural', 'Vegan']
['Natural']
['Natural']
['Vegan']
['Vegan']
['Canadian', 'Gluten Free', 'Natural', 'Non-GMO', 'Peanut Free Product']
['Gluten Free', 'Natural']
['Canadian', 'Gluten Free', 'Natural', 'Organic']
['Gluten Free']
['Gluten Free', 'Natural']
['Canadian', 'Gluten Free']
['Vegan']
['Gluten Free', 'Natural']
['Natural']
['Vegan']
['Vegan']
['Canadian', 'Natural']
['Canadian', 'Natural', 'Vegan']
['Natural', 'Vegan']
['Gluten Free', 'Natural']
['Natural', 'Vegan']
['Gluten Free', 'Natural']
['Gluten Free', 'Natural']
['Canadian', 'Gluten Free', 'Natural']

### New Tag list without Duplicates

In [15]:
no_nan_values['tag_list'].value_counts()

tag_list
(Gluten Free,)                                                                          29
(Vegan,)                                                                                23
(Canadian, Natural)                                                                     19
(Gluten Free, Natural)                                                                  15
(Natural,)                                                                              10
(Natural, Vegan)                                                                         9
(Gluten Free, Natural, Vegan)                                                            6
(Canadian,)                                                                              4
(Canadian, Gluten Free, Natural, Non-GMO, Vegan)                                         3
(Canadian, Natural, Vegan)                                                               3
(Canadian, Gluten Free)                                                                  3
(Natural, Organic)                                                                       2
(Canadian, Dairy Free, Fair Trade, Gluten Free, Natural, Non-GMO, Sugar Free, Vegan)     2
(Canadian, Gluten Free, Natural, Organic, Vegan)                                         1
(Canadian, Gluten Free, Natural, Non-GMO, Peanut Free Product)                           1
(Canadian, Gluten Free, Natural, Organic)                                                1
(Canadian, Gluten Free, Natural)                                                         1
Name: count, dtype: int64

In [16]:
type(no_nan_values['tag_list'].iloc[0])

tuple

## Data Exploration

### Average rating for each unique combination of tag_list

In [23]:
no_nan_values.groupby('tag_list')['rating'].mean().round(2).reset_index().sort_values(by='rating')

                                             tag_list  rating
1   (Canadian, Dairy Free, Fair Trade, Gluten Free...    2.50
7    (Canadian, Gluten Free, Natural, Organic, Vegan)    3.30
9                          (Canadian, Natural, Vegan)    3.43
11                             (Gluten Free, Natural)    3.86
0                                         (Canadian,)    3.90
8                                 (Canadian, Natural)    4.17
2                             (Canadian, Gluten Free)    4.17
13                                         (Natural,)    4.24
4   (Canadian, Gluten Free, Natural, Non-GMO, Pean...    4.30
16                                           (Vegan,)    4.41
12                      (Gluten Free, Natural, Vegan)    4.42
15                                   (Natural, Vegan)    4.46
10                                     (Gluten Free,)    4.52
5    (Canadian, Gluten Free, Natural, Non-GMO, Vegan)    4.57
3                    (Canadian, Gluten Free, Natural)    4.60
6           (Canadian, Gluten Free, Natural, Organic)    4.80
14                                 (Natural, Organic)    5.00

In [26]:
new_pivot = no_nan_values.pivot_table(values="id", index='rating', columns='tag_list', aggfunc='mean')
new_pivot

tag_list,"(Canadian,)","(Canadian, Dairy Free, Fair Trade, Gluten Free, Natural, Non-GMO, Sugar Free, Vegan)","(Canadian, Gluten Free)","(Canadian, Gluten Free, Natural)","(Canadian, Gluten Free, Natural, Non-GMO, Peanut Free Product)","(Canadian, Gluten Free, Natural, Non-GMO, Vegan)","(Canadian, Gluten Free, Natural, Organic)","(Canadian, Gluten Free, Natural, Organic, Vegan)","(Canadian, Natural)","(Canadian, Natural, Vegan)","(Gluten Free,)","(Gluten Free, Natural)","(Gluten Free, Natural, Vegan)","(Natural,)","(Natural, Organic)","(Natural, Vegan)","(Vegan,)"
rating,,,,,,,,,,,,,,,,,
2.0,NaN,165.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,416.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,388.000,484.0,NaN,NaN,NaN,NaN,NaN
2.6,287.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.0,244.0,156.0,403.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,467.0,NaN,188.0,NaN
3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,NaN
3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0,NaN,NaN,NaN,NaN,NaN
3.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,191.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122.0,NaN,54.0,NaN,NaN,NaN,NaN,NaN
3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,278.0,NaN,NaN,NaN,NaN
3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.5,NaN,70.0,NaN,NaN,287.500000
3.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.5,NaN,462.000,NaN,NaN,385.0,NaN,NaN,315.000000
3.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,239.5,NaN,NaN,4.0,234.0,NaN,NaN,NaN,NaN
4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,252.0,NaN,393.500,274.4,NaN,NaN,NaN,NaN,287.000000
4.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.000000
4.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
4.3,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,367.0,NaN,NaN,NaN,NaN,71.5,NaN,182.5,172.500000
4.4,NaN,NaN,NaN,NaN,NaN,437.0,NaN,NaN,NaN,NaN,NaN,NaN,392.0,136.0,NaN,NaN,478.000000
4.5,NaN,NaN,38.0,NaN,NaN,275.0,NaN,NaN,360.5,NaN,323.000,252.0,NaN,62.0,NaN,NaN,171.000000
4.6,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,230.000,NaN,283.0,483.0,NaN,NaN,NaN
4.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,379.000,NaN,NaN,NaN,NaN,323.0,441.000000
4.8,NaN,NaN,NaN,NaN,NaN,126.0,50.0,NaN,NaN,NaN,337.000,NaN,NaN,290.0,NaN,16.0,229.333333
4.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,438.0,NaN,NaN,NaN,281.0,NaN
5.0,403.5,NaN,201.0,NaN,NaN,NaN,NaN,NaN,309.5,NaN,296.875,459.0,278.0,310.0,280.0,129.0,183.800000