# Ingredients effect on ratings : Sheryl

In [28]:
import pandas as pd

In [8]:
makeup_data = pd.read_csv("/Users/sherylboateng/Desktop/TEPP_Data_Project/data/processed/clean_makeup.csv")

makeup_data.head()
makeup_data.info()
makeup_data.describe().round(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 931 entries, 0 to 930
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            931 non-null    int64
 1   brand         919 non-null    object
 2   name          931 non-null    object
 3   category      507 non-null    object
 4   product_type  931 non-null    object
 5   price         917 non-null    float64
 6   currency      368 non-null    object
 7   tag_list      931 non-null    object
 8   rating        340 non-null    float64
dtypes: float64(2), int64(1), object(6)
memory usage: 65.6+ KB

            id   price  rating
count   931.00  917.00  340.00
mean    531.16   16.51    4.32
std     311.05   11.03    0.68
min       1.00    0.00    1.50
25%     263.00    8.99    4.00
50%     518.00   13.99    4.50
75%     814.50   22.00    5.00
max    1048.00   77.00    5.00

In [50]:
no_nan_values = makeup_data[makeup_data['rating'].notna() & (makeup_data['tag_list'] != '[]')]
no_nan_values.head()

,id,brand,name,category,product_type,price,currency,tag_list,rating
477,503,physicians formula,Physicians Formula Super BB InstaReady Filter ...,NaN,bronzer,19.99,NaN,"['Gluten Free', 'Natural']",4.0
489,490,NaN,Earth Lab Loose Mineral Bronzer,NaN,bronzer,24.00,NaN,"['Canadian', 'Natural']",5.0
492,487,physicians formula,Physicians Formula Bronze Booster Airbrushing ...,NaN,bronzer,19.99,NaN,['Gluten Free'],5.0
494,485,milani,Milani Baked Bronzer,NaN,bronzer,9.99,NaN,['Vegan'],4.0
495,484,physicians formula,Physicians Formula Organic Wear 100% Natural O...,NaN,bronzer,21.99,NaN,"['Gluten Free', 'Natural']",2.5

In [51]:

no_nan_values.groupby('tag_list')['rating'].sum().sort_index(ascending=False)

tag_list
['Vegan']                                                                                               101.5
['Vegan', 'Natural']                                                                                     31.1
['Vegan', 'Gluten Free', 'Natural']                                                                      26.5
['Organic', 'Natural']                                                                                   10.0
['Natural']                                                                                              42.4
['Natural', 'Vegan']                                                                                      9.0
['Natural', 'Vegan', 'Gluten Free', 'Non-GMO', 'Canadian']                                               13.7
['Natural', 'Vegan', 'Gluten Free', 'Fair Trade', 'Sugar Free', 'Non-GMO', 'Dairy Free', 'Canadian']      5.0
['Natural', 'Vegan', 'Canadian']                                                                          3.4
['Natural', 'Organic', 'Vegan', 'Gluten Free', 'Canadian']                                                3.3
['Natural', 'Organic', 'Gluten Free', 'Canadian']                                                         4.8
['Natural', 'Gluten Free']                                                                               13.9
['Natural', 'Gluten Free', 'Non-GMO', 'Peanut Free Product', 'Canadian']                                  4.3
['Natural', 'Gluten Free', 'Canadian']                                                                    4.6
['Natural', 'Canadian']                                                                                   4.1
['Gluten Free']                                                                                         131.1
['Gluten Free', 'Natural']                                                                               44.0
['Canadian']                                                                                             15.6
['Canadian', 'Vegan', 'Natural']                                                                          6.9
['Canadian', 'Natural']                                                                                  75.1
['Canadian', 'Gluten Free']                                                                              12.5
Name: rating, dtype: float64

In [52]:
new_pivot = no_nan_values.pivot_table(values="id", index='rating', columns='tag_list', aggfunc='sum')
new_pivot

tag_list,"['Canadian', 'Gluten Free']","['Canadian', 'Natural']","['Canadian', 'Vegan', 'Natural']",['Canadian'],"['Gluten Free', 'Natural']",['Gluten Free'],"['Natural', 'Canadian']","['Natural', 'Gluten Free', 'Canadian']","['Natural', 'Gluten Free', 'Non-GMO', 'Peanut Free Product', 'Canadian']","['Natural', 'Gluten Free']",...,"['Natural', 'Organic', 'Vegan', 'Gluten Free', 'Canadian']","['Natural', 'Vegan', 'Canadian']","['Natural', 'Vegan', 'Gluten Free', 'Fair Trade', 'Sugar Free', 'Non-GMO', 'Dairy Free', 'Canadian']","['Natural', 'Vegan', 'Gluten Free', 'Non-GMO', 'Canadian']","['Natural', 'Vegan']",['Natural'],"['Organic', 'Natural']","['Vegan', 'Gluten Free', 'Natural']","['Vegan', 'Natural']",['Vegan']
rating,,,,,,,,,,,,,,,,,,,,,
2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,165.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.3,NaN,416.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.5,NaN,NaN,NaN,NaN,484.0,388.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.6,NaN,NaN,NaN,287.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.0,403.0,NaN,NaN,244.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,156.0,NaN,NaN,467.0,NaN,NaN,188.0,NaN
3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,191.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.4,NaN,NaN,227.0,NaN,54.0,NaN,NaN,NaN,NaN,NaN,...,NaN,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.5,NaN,NaN,187.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,278.0,NaN,NaN
3.7,NaN,NaN,NaN,NaN,196.0,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,NaN,575.0
3.8,NaN,215.0,NaN,NaN,NaN,462.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,385.0,NaN,NaN,NaN,315.0
3.9,NaN,479.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,234.0,NaN,NaN
4.0,NaN,1260.0,NaN,NaN,1372.0,2361.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1148.0
4.1,NaN,316.0,NaN,NaN,NaN,NaN,21.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0
4.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN
4.3,NaN,367.0,NaN,NaN,NaN,NaN,NaN,NaN,55.0,NaN,...,NaN,NaN,NaN,NaN,NaN,143.0,NaN,NaN,365.0,690.0
4.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,437.0,NaN,136.0,NaN,392.0,NaN,478.0
4.5,38.0,721.0,NaN,NaN,252.0,646.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,275.0,NaN,62.0,NaN,NaN,NaN,171.0
4.6,NaN,NaN,NaN,NaN,NaN,690.0,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,483.0,NaN,283.0,NaN,NaN
4.7,NaN,NaN,NaN,NaN,NaN,1516.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,323.0,441.0
4.8,NaN,NaN,NaN,NaN,NaN,1348.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,126.0,16.0,290.0,NaN,NaN,NaN,688.0
4.9,NaN,NaN,NaN,NaN,438.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,562.0,NaN
5.0,201.0,1238.0,NaN,807.0,459.0,2375.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,310.0,560.0,556.0,129.0,919.0